# Wire Rod v1.2.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

defaultLevel: 4
cost: 10
speed: 3
raiseBase: false
revive: true
reviveSeconds: 5
reviveAmount: 30
