name: WireRod
main: com.github.ucchyocean.WireRod
version: 2.0.0
author: ucchy
description: WireRod is the magic battle item.
softdepend: [ColorTeaming]
commands:
  wirerod:
    description: WireRod is the magic battle item.
    aliases: [wi,wr]
    usage: |
           /<command> get [level] - Get new WireRod.
           /<command> give (player) [level] - Give new WireRod.
           /<command> reload - Reload config.yml.
    permission: wirerod.command
    permission-message: You don't have permission "<permission>".
permissions:
  wirerod.command:
    description: WireRod command permission.
    default: true
  wirerod.reload:
    description: WireRod reload command permission.
    default: op
  wirerod.get:
    description: WireRod get command permission.
    default: true
  wirerod.give:
    description: WireRod give command permission.
    default: op
  wirerod.action:
    description: WireRod action permission.
    default: true
  wirerod.*:
    children:
      wirerod.command: true
      wirerod.reload: true
      wirerod.get: true
      wirerod.give: true
      wirerod.action: true
    description: All of WireRod permission.
